version: '3'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - last-message-network

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    ports:
      - "4444:4444"
    networks:
      - last-message-network
    environment:
      FLAG: jail{py7h0n_f20n73nd_py7h0n_84ck3nd_w007_2eec3c62f4905ab5e295ae}
    depends_on:
      - app

networks:
  last-message-network:
    driver: bridge

